/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;


import java.sql.Statement;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import javax.swing.JTable;

/**
 *
 * @author HP
 */

public class Formulaire extends javax.swing.JFrame {
    /**
     * Creates new form Form
     */
    public Formulaire() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        supprimerEtudiant = new javax.swing.JButton();
        ajouterEtudiant = new javax.swing.JButton();
        modifierEtudiant = new javax.swing.JButton();
        afficherEtudiant = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        supprimerEtudiant.setBackground(new java.awt.Color(204, 0, 0));
        supprimerEtudiant.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        supprimerEtudiant.setForeground(new java.awt.Color(255, 255, 255));
        supprimerEtudiant.setText("Supprimer");
        supprimerEtudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerEtudiantActionPerformed(evt);
            }
        });

        ajouterEtudiant.setBackground(new java.awt.Color(0, 153, 51));
        ajouterEtudiant.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        ajouterEtudiant.setForeground(new java.awt.Color(255, 255, 255));
        ajouterEtudiant.setText("Ajouter");
        ajouterEtudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterEtudiantActionPerformed(evt);
            }
        });

        modifierEtudiant.setBackground(new java.awt.Color(0, 0, 153));
        modifierEtudiant.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        modifierEtudiant.setForeground(new java.awt.Color(255, 255, 255));
        modifierEtudiant.setText("Modifier");
        modifierEtudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierEtudiantActionPerformed(evt);
            }
        });

        afficherEtudiant.setBackground(new java.awt.Color(153, 153, 153));
        afficherEtudiant.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        afficherEtudiant.setForeground(new java.awt.Color(255, 255, 255));
        afficherEtudiant.setText("Afficher");
        afficherEtudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afficherEtudiantActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Prenom :");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Email :");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Telephone :");

        jTextField1.setBackground(new java.awt.Color(214, 217, 223));
        jTextField1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField1.setToolTipText("Entrez votre Nom");
        jTextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 5, 1));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField5.setBackground(new java.awt.Color(214, 217, 223));
        jTextField5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField5.setToolTipText("Entrez votre prénom");
        jTextField5.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 5, 1));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Nom :");

        jTextField6.setBackground(new java.awt.Color(214, 217, 223));
        jTextField6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField6.setToolTipText("Entrez votre adresse mail");
        jTextField6.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 5, 1));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jTextField7.setBackground(new java.awt.Color(214, 217, 223));
        jTextField7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jTextField7.setToolTipText("Entrez votre numéro de téléphone");
        jTextField7.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 1, 5, 1));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setText("Informations de l'étudiant(e)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(supprimerEtudiant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(modifierEtudiant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ajouterEtudiant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(afficherEtudiant, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(ajouterEtudiant)
                        .addGap(32, 32, 32)
                        .addComponent(modifierEtudiant)
                        .addGap(35, 35, 35)
                        .addComponent(supprimerEtudiant)
                        .addGap(31, 31, 31)
                        .addComponent(afficherEtudiant)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void ajouterEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterEtudiantActionPerformed
        // TODO add your handling code here:
        String Nom = jTextField1.getText();
        String Prenom = jTextField5.getText();
        String Email = jTextField6.getText();
        String Telephone = jTextField7.getText();
        
        String sql = "INSERT INTO etudiants(Nom, Prenom, Email, Telephone) "
                + "VALUES(?,?,?,?)";
        
        if (Nom.trim().isEmpty() || Prenom.trim().isEmpty() || 
                Email.trim().isEmpty() || Telephone.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, 
                "Tous les champs doivent être remplis avant d'ajouter", 
                "Erreur", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            Connection conn = ConnectionDB.getConnection();
            PreparedStatement smt = conn.prepareStatement(sql);
            smt.setString(1, Nom);
            smt.setString(2, Prenom);
            smt.setString(3, Email);
            smt.setString(4, Telephone);
            
            int confirmAjout = smt.executeUpdate();
            if(confirmAjout > 0){
                JOptionPane.showMessageDialog(null, 
                    "L'étudiant " + Nom + " " + Prenom + " a été ajouté avec"
                            + "succès", 
                    "Confirmation",
                    JOptionPane.INFORMATION_MESSAGE);
                
                ListeEtudiants.getInstance().rafraichirTableau();
                
                reinitialiserFormulaire();
           
            }else{
                JOptionPane.showConfirmDialog(null, "L'ajout de l'étudiant " 
                        +Nom + " " + Prenom + " a échoué",
                        "Erreur",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch(SQLException ex){
            System.err.println("Erreur lors de l'ajout: " + ex.getMessage());
            JOptionPane.showMessageDialog(null, 
                "Erreur lors de l'ajout: " + ex.getMessage(), 
                "Erreur de base de données", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ajouterEtudiantActionPerformed

    private void afficherEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afficherEtudiantActionPerformed
        // TODO add your handling code here:
        String sql = "SELECT * FROM etudiants";
        
        try{
            Connection conn = ConnectionDB.getConnection();
            Statement smt = conn.createStatement();
            
            ResultSet resultat = smt.executeQuery(sql);
            
            ListeEtudiants affichage = ListeEtudiants.getInstance();
            JTable jTable1 = affichage.getJTable1();
            
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            
            model.setRowCount(0);
            
            while(resultat.next()){
                Object[] Ligne = { resultat.getInt("id"),
                    resultat.getString("Nom"),
                    resultat.getString("Prenom"),
                    resultat.getString("Email"),
                    resultat.getString("Telephone"),
                };
                model.addRow(Ligne);
            }
            
            affichage.setVisible(true);
            
        }catch(SQLException ex){
            System.out.println("Erreur lors de la récupération des étudiants: "
                    + ex.getMessage());
            JOptionPane.showMessageDialog(this, 
                "Erreur lors de la récupération des données", 
                "Erreur", 
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_afficherEtudiantActionPerformed

    private int currentId = -1;
    private void modifierEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierEtudiantActionPerformed
        // TODO add your handling code here:
        if(currentId == -1){
            String idStr = JOptionPane.showInputDialog(this, "Entrez l'ID de l'etudiant"
                    + " à modifier:", "Recherche d'étudiant", JOptionPane.QUESTION_MESSAGE);
            if(idStr != null && !idStr.isEmpty()){
                try{
                    int id = Integer.parseInt(idStr);
                    rechercherEtudiantParId(id);
                }catch(NumberFormatException ex){
                    JOptionPane.showMessageDialog(this, "Veuillez entrer un ID valide"
                            + " (entier > 0", 
                            "Erreur", JOptionPane.ERROR_MESSAGE);
                }
            }
        }else{
            String Nom = jTextField1.getText();
            String Prenom = jTextField5.getText();
            String Email = jTextField6.getText();
            String Telephone = jTextField7.getText();

            if(Nom.isEmpty() || Prenom.isEmpty() || Email.isEmpty() || 
                    Telephone.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs", 
                        "Erreur", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if(ListeEtudiants.modifierEtudiant(currentId, Nom, Prenom, 
                    Email, Telephone)) {
                JOptionPane.showMessageDialog(this, """
                        \u00c9tudiant(e) modifi\u00e9 avec succ\u00e8s. 
                        Nom: """ + Nom + "\nPrénom : " + Prenom + 
                        "\nEmail : " + Email + "\nTélephone : " + Telephone, 
                        "Succès", JOptionPane.INFORMATION_MESSAGE);
                
                ListeEtudiants.getInstance().rafraichirTableau();
                
                reinitialiserFormulaire();
                
            } else {
                JOptionPane.showMessageDialog(this, "Erreur lors de la modification", 
                        "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_modifierEtudiantActionPerformed

    private void supprimerEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerEtudiantActionPerformed
        // TODO add your handling code here:
        
        String idStr = JOptionPane.showInputDialog(this, "Entrez l'ID de l'etudiant(e)"
                + "à supprimer:", "Suppression d'étudiant", JOptionPane.QUESTION_MESSAGE);
        if(idStr != null && !idStr.isEmpty()){
            
            try{
                int id = Integer.parseInt(idStr);
                int confirm = JOptionPane.showConfirmDialog(this,
                "Êtes-vous sûr de vouloir supprimer l'étudiant(e) avec l'ID = " + id + "?",
                "Confirmer la suppression",
                JOptionPane.YES_NO_OPTION);
                
                
                if (confirm == JOptionPane.YES_OPTION) {
                    String[] resultSupp = ListeEtudiants.supprimerEtudiant(id);
                    if("succès".equals(resultSupp[0])) {
                        JOptionPane.showMessageDialog(this,
                            "L'étudiant(e) " + resultSupp[1] + " " + resultSupp[2] + 
                                    " (ID: " + id + ") a été supprimé(e) avec succès",
                            "Succès",
                            JOptionPane.INFORMATION_MESSAGE);

                        ListeEtudiants.getInstance().rafraichirTableau();
                        
                    } else if("non_trouvé".equals(resultSupp[0])) {
                        JOptionPane.showMessageDialog(this,
                            "Aucun(e) étudiant(e) trouvé pour la suppression !\n l'ID = " + id + 
                                    " n'existe pas dans la base de données",
                            "Erreur",
                            JOptionPane.ERROR_MESSAGE);
                    }else{
                        JOptionPane.showMessageDialog(this, "Erreur lors de la"
                                + " suppression! Non connecté à la base de données.", 
                                "Erreur", 
                                JOptionPane.ERROR_MESSAGE);
                    }
                }
            }catch(NumberFormatException ex){
                JOptionPane.showMessageDialog(this, "Veuillez entrer un ID valide"
                        + "(nombre entier > 0)", 
                        "Erreur", 
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_supprimerEtudiantActionPerformed


    // Méthode pour réinitialiser le formulaire
    private void reinitialiserFormulaire() {
        currentId = -1;
        jTextField1.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
    }
    
    private void rechercherEtudiantParId(int id) {
        String sql = "SELECT * FROM etudiants WHERE id = ?";

        try {
            Connection conn = ConnectionDB.getConnection();
            PreparedStatement smt = conn.prepareStatement(sql);
            smt.setInt(1, id);
            ResultSet resultat = smt.executeQuery();

            if (resultat.next()) {
                // Remplir le formulaire avec les données trouvées
                currentId = id;
                jTextField1.setText(resultat.getString("Nom"));
                jTextField5.setText(resultat.getString("Prenom"));
                jTextField6.setText(resultat.getString("Email"));
                jTextField7.setText(resultat.getString("Telephone"));
            } else {
                JOptionPane.showMessageDialog(this, 
                    "Aucun étudiant trouvé avec l'ID " + id, 
                    "Erreur", 
                    JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, 
                "Erreur de base de données: " + ex.getMessage(), 
                "Erreur", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulaire.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulaire().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton afficherEtudiant;
    private javax.swing.JButton ajouterEtudiant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JButton modifierEtudiant;
    private javax.swing.JButton supprimerEtudiant;
    // End of variables declaration//GEN-END:variables
}
